name: pyoccenv
channels:
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=4.5
  - aiohttp=3.8.4
  - aiosignal=1.3.1
  - alsa-lib=1.2.8
  - aom=3.5.0
  - async-timeout=4.0.2
  - attr=2.5.1
  - attrs=22.2.0
  - bzip2=1.0.8
  - c-ares=1.18.1
  - ca-certificates=2022.12.7
  - certifi=2022.12.7
  - charset-normalizer=2.1.1
  - curl=7.87.0
  - dbus=1.13.6
  - double-conversion=3.2.0
  - eigen=3.4.0
  - expat=2.5.0
  - ffmpeg=5.1.2
  - fftw=3.3.10
  - font-ttf-dejavu-sans-mono=2.37
  - font-ttf-inconsolata=3.000
  - font-ttf-source-code-pro=2.038
  - font-ttf-ubuntu=0.83
  - fontconfig=2.14.2
  - fonts-conda-ecosystem=1
  - fonts-conda-forge=1
  - freeimage=3.18.0
  - freetype=2.12.1
  - frozenlist=1.3.3
  - gettext=0.21.1
  - gl2ps=1.4.2
  - glew=2.1.0
  - glib=2.74.1
  - glib-tools=2.74.1
  - gmp=6.2.1
  - gnutls=3.7.8
  - gst-plugins-base=1.21.3
  - gstreamer=1.21.3
  - gstreamer-orc=0.4.33
  - hdf4=4.2.15
  - hdf5=1.12.2
  - icu=70.1
  - idna=3.4
  - imath=3.1.6
  - jack=1.9.22
  - jpeg=9e
  - jsoncpp=1.9.5
  - jxrlib=1.1
  - keyutils=1.6.1
  - krb5=1.19.3
  - lame=3.100
  - lcms2=2.14
  - ld_impl_linux-64=2.38
  - lerc=4.0.0
  - libaec=1.0.6
  - libblas=3.9.0
  - libcap=2.66
  - libcblas=3.9.0
  - libclang=15.0.7
  - libclang13=15.0.7
  - libcups=2.3.3
  - libcurl=7.87.0
  - libdb=6.2.32
  - libdeflate=1.17
  - libdrm=2.4.114
  - libedit=3.1.20191231
  - libev=4.33
  - libevent=2.1.10
  - libffi=3.4.2
  - libflac=1.4.2
  - libgcc-ng=12.2.0
  - libgcrypt=1.10.1
  - libgfortran-ng=12.2.0
  - libgfortran5=12.2.0
  - libglib=2.74.1
  - libglu=9.0.0
  - libgpg-error=1.46
  - libhwloc=2.8.0
  - libiconv=1.17
  - libidn2=2.3.4
  - liblapack=3.9.0
  - libllvm15=15.0.7
  - libnetcdf=4.8.1
  - libnghttp2=1.51.0
  - libogg=1.3.4
  - libopenblas=0.3.21
  - libopus=1.3.1
  - libpciaccess=0.17
  - libpng=1.6.39
  - libpq=14.5
  - libraw=0.21.1
  - libsndfile=1.2.0
  - libsqlite=3.40.0
  - libssh2=1.10.0
  - libstdcxx-ng=12.2.0
  - libsystemd0=252
  - libtasn1=4.19.0
  - libtheora=1.1.1
  - libtiff=4.5.0
  - libtool=2.4.7
  - libudev1=252
  - libunistring=0.9.10
  - libuuid=2.32.1
  - libva=2.17.0
  - libvorbis=1.3.7
  - libvpx=1.11.0
  - libwebp-base=1.2.4
  - libxcb=1.13
  - libxkbcommon=1.5.0
  - libxml2=2.10.3
  - libzip=1.9.2
  - libzlib=1.2.13
  - llvm-openmp=15.0.7
  - loguru=0.6.0
  - lz4-c=1.9.4
  - mpg123=1.31.2
  - multidict=6.0.4
  - mysql-common=8.0.32
  - mysql-libs=8.0.32
  - ncurses=6.4
  - nettle=3.8.1
  - nlohmann_json=3.11.2
  - nspr=4.35
  - nss=3.88
  - numpy=1.24.2
  - occt=7.7.0
  - openexr=3.1.5
  - openh264=2.3.1
  - openjpeg=2.5.0
  - openssl=1.1.1t
  - p11-kit=0.24.1
  - pcre2=10.40
  - pip=22.3.1
  - proj=9.1.1
  - pthread-stubs=0.4
  - pugixml=1.11.4
  - pulseaudio=16.1
  - pyparsing=3.0.9
  - python=3.9.16
  - python_abi=3.9
  - pythonocc-core=7.7.0
  - qt-main=5.15.6
  - rapidjson=1.1.0
  - readline=8.2
  - setuptools=65.6.3
  - six=1.16.0
  - sqlite=3.40.1
  - svgwrite=1.4.3
  - svt-av1=1.4.1
  - tbb=2021.7.0
  - tbb-devel=2021.7.0
  - tk=8.6.12
  - typing-extensions=4.4.0
  - typing_extensions=4.4.0
  - utfcpp=3.2.3
  - vtk=9.2.5
  - wheel=0.38.4
  - wslink=1.10.1
  - x264=1!164.3095
  - x265=3.5
  - xcb-util=0.4.0
  - xcb-util-image=0.4.0
  - xcb-util-keysyms=0.4.0
  - xcb-util-renderutil=0.3.9
  - xcb-util-wm=0.4.1
  - xorg-fixesproto=5.0
  - xorg-kbproto=1.0.7
  - xorg-libice=1.0.10
  - xorg-libsm=1.2.3
  - xorg-libx11=1.7.2
  - xorg-libxau=1.0.9
  - xorg-libxdmcp=1.1.3
  - xorg-libxext=1.3.4
  - xorg-libxfixes=5.0.3
  - xorg-libxt=1.2.1
  - xorg-xextproto=7.3.0
  - xorg-xproto=7.0.31
  - xz=5.2.10
  - yarl=1.8.2
  - zlib=1.2.13
  - zstd=1.5.2
  - pip:
      - altair==4.2.2
      - blinker==1.5
      - cachetools==5.3.0
      - click==8.1.3
      - decorator==5.1.1
      - entrypoints==0.4
      - gitdb==4.0.10
      - gitpython==3.1.31
      - importlib-metadata==6.0.0
      - jinja2==3.1.2
      - jsonschema==4.17.3
      - markdown-it-py==2.1.0
      - markupsafe==2.1.2
      - mdurl==0.1.2
      - packaging==23.0
      - pandas==1.5.3
      - pillow==9.4.0
      - protobuf==3.20.3
      - pyarrow==11.0.0
      - pydeck==0.8.0
      - pygments==2.14.0
      - pympler==1.0.1
      - pyrsistent==0.19.3
      - python-dateutil==2.8.2
      - pytz==2022.7.1
      - pytz-deprecation-shim==0.1.0.post0
      - requests==2.28.2
      - rich==13.3.1
      - semver==2.13.0
      - smmap==5.0.0
      - streamlit==1.18.1
      - toml==0.10.2
      - toolz==0.12.0
      - tornado==6.2
      - tzdata==2022.7
      - tzlocal==4.2
      - urllib3==1.26.14
      - validators==0.20.0
      - watchdog==2.2.1
      - zipp==3.14.0
