name: pythonocc_st-env
channels:
  - conda-forge
  - defaults
dependencies:
  - aiohttp=3.8.4
  - aiosignal=1.3.1
  - aom=3.5.0
  - async-timeout=4.0.2
  - attrs=22.2.0
  - bzip2=1.0.8
  - ca-certificates=2022.12.7
  - charset-normalizer=2.1.1
  - colorama=0.4.6
  - curl=7.88.0
  - double-conversion=3.2.0
  - eigen=3.4.0
  - expat=2.5.0
  - ffmpeg=5.1.2
  - font-ttf-dejavu-sans-mono=2.37
  - font-ttf-inconsolata=3.000
  - font-ttf-source-code-pro=2.038
  - font-ttf-ubuntu=0.83
  - fontconfig=2.14.2
  - fonts-conda-ecosystem=1
  - fonts-conda-forge=1
  - freeimage=3.18.0
  - freetype=2.12.1
  - frozenlist=1.3.3
  - gettext=0.21.1
  - gl2ps=1.4.2
  - glew=2.1.0
  - glib=2.74.1
  - glib-tools=2.74.1
  - gst-plugins-base=1.22.0
  - gstreamer=1.22.0
  - hdf4=4.2.15
  - hdf5=1.12.2
  - icu=70.1
  - idna=3.4
  - imath=3.1.6
  - intel-openmp=2023.0.0
  - jpeg=9e
  - jsoncpp=1.9.5
  - jxrlib=1.1
  - krb5=1.20.1
  - lcms2=2.14
  - lerc=4.0.0
  - libaec=1.0.6
  - libblas=3.9.0
  - libcblas=3.9.0
  - libclang=15.0.7
  - libclang13=15.0.7
  - libcurl=7.88.0
  - libdeflate=1.17
  - libffi=3.4.2
  - libglib=2.74.1
  - libhwloc=2.8.0
  - libiconv=1.17
  - liblapack=3.9.0
  - libnetcdf=4.9.1
  - libogg=1.3.4
  - libopus=1.3.1
  - libpng=1.6.39
  - libraw=0.21.1
  - libsqlite=3.40.0
  - libssh2=1.10.0
  - libtheora=1.1.1
  - libtiff=4.5.0
  - libvorbis=1.3.7
  - libwebp-base=1.2.4
  - libxml2=2.10.3
  - libzip=1.9.2
  - libzlib=1.2.13
  - loguru=0.6.0
  - lz4-c=1.9.4
  - mkl=2022.1.0
  - multidict=6.0.4
  - nlohmann_json=3.11.2
  - numpy=1.24.2
  - occt=7.7.0
  - openexr=3.1.5
  - openh264=2.3.1
  - openjpeg=2.5.0
  - openssl=3.0.8
  - pcre2=10.40
  - pip=23.0.1
  - proj=9.1.1
  - pthreads-win32=2.9.1
  - pugixml=1.11.4
  - pyparsing=3.0.9
  - python=3.9.16
  - python_abi=3.9
  - pythonocc-core=7.7.0
  - qt-main=5.15.8
  - rapidjson=1.1.0
  - setuptools=67.3.1
  - six=1.16.0
  - sqlite=3.40.0
  - svgwrite=1.4.3
  - svt-av1=1.4.1
  - tbb=2021.7.0
  - tbb-devel=2021.7.0
  - tk=8.6.12
  - typing-extensions=4.4.0
  - typing_extensions=4.4.0
  - ucrt=10.0.22621.0
  - utfcpp=3.2.3
  - vc=14.3
  - vs2015_runtime=14.34.31931
  - vtk=9.2.5
  - wheel=0.38.4
  - win32_setctime=1.1.0
  - wslink=1.10.1
  - x264=1!164.3095
  - x265=3.5
  - xz=5.2.6
  - yarl=1.8.2
  - zlib=1.2.13
  - zstd=1.5.2
  - pip:
      - altair==4.2.2
      - anyio==3.6.2
      - appdirs==1.4.4
      - argon2-cffi==21.3.0
      - argon2-cffi-bindings==21.2.0
      - arrow==1.2.3
      - asttokens==2.2.1
      - backcall==0.2.0
      - beautifulsoup4==4.11.2
      - bleach==6.0.0
      - blinker==1.5
      - cachetools==5.3.0
      - certifi==2022.12.7
      - cffi==1.15.1
      - click==8.1.3
      - comm==0.1.2
      - configargparse==1.5.3
      - contourpy==1.0.7
      - cycler==0.11.0
      - dash==2.8.1
      - dash-core-components==2.0.0
      - dash-html-components==2.0.0
      - dash-table==5.0.0
      - debugpy==1.6.6
      - decorator==5.1.1
      - defusedxml==0.7.1
      - entrypoints==0.4
      - executing==1.2.0
      - fastjsonschema==2.16.2
      - flask==2.2.3
      - fonttools==4.38.0
      - fqdn==1.5.1
      - gitdb==4.0.10
      - gitpython==3.1.30
      - imageio==2.25.1
      - importlib-metadata==6.0.0
      - importlib-resources==5.10.2
      - ipydatawidgets==4.3.2
      - ipykernel==6.21.2
      - ipython==8.4.0
      - ipython-genutils==0.2.0
      - ipywidgets==7.7.1
      - isoduration==20.11.0
      - itsdangerous==2.1.2
      - jedi==0.18.2
      - jsonpointer==2.3
      - jsonschema==4.17.3
      - jupyter-client==8.0.2
      - jupyter-core==5.2.0
      - jupyter-events==0.6.3
      - jupyter-server==2.3.0
      - jupyter-server-terminals==0.4.4
      - jupyterlab-pygments==0.2.2
      - jupyterlab-widgets==3.0.5
      - kiwisolver==1.4.4
      - markdown-it-py==2.1.0
      - markupsafe==2.1.2
      - matplotlib==3.7.0
      - matplotlib-inline==0.1.6
      - mdurl==0.1.2
      - mistune==2.0.5
      - nbclassic==0.5.1
      - nbclient==0.7.2
      - nbconvert==7.2.9
      - nbformat==5.5.0
      - nest-asyncio==1.5.6
      - notebook==6.5.2
      - notebook-shim==0.2.2
      - packaging==23.0
      - pandas==1.5.3
      - pandocfilters==1.5.0
      - parso==0.8.3
      - pickleshare==0.7.5
      - pillow==9.4.0
      - platformdirs==3.0.0
      - pooch==1.6.0
      - prometheus-client==0.16.0
      - prompt-toolkit==3.0.36
      - protobuf==3.20.3
      - psutil==5.9.4
      - pure-eval==0.2.2
      - pyarrow==11.0.0
      - pycparser==2.21
      - pydeck==0.8.0
      - pygments==2.14.0
      - pympler==1.0.1
      - pyrsistent==0.19.3
      - python-dateutil==2.8.2
      - python-json-logger==2.0.6
      - pythreejs==2.4.1
      - pytz==2022.7.1
      - pytz-deprecation-shim==0.1.0.post0
      - pywinpty==2.0.10
      - pyyaml==6.0
      - pyzmq==25.0.0
      - requests==2.28.2
      - rfc3339-validator==0.1.4
      - rfc3986-validator==0.1.1
      - rich==13.3.1
      - scipy==1.10.0
      - scooby==0.7.1
      - semver==2.13.0
      - send2trash==1.8.0
      - smmap==5.0.0
      - sniffio==1.3.0
      - soupsieve==2.4
      - stack-data==0.6.2
      - streamlit==1.18.1
      - tenacity==8.2.1
      - terminado==0.17.1
      - tinycss2==1.2.1
      - toml==0.10.2
      - toolz==0.12.0
      - tornado==6.2
      - traitlets==5.9.0
      - traittypes==0.2.1
      - tzdata==2022.7
      - tzlocal==4.2
      - uri-template==1.2.0
      - urllib3==1.26.14
      - validators==0.20.0
      - watchdog==2.2.1
      - wcwidth==0.2.6
      - webcolors==1.12
      - webencodings==0.5.1
      - websocket-client==1.5.1
      - werkzeug==2.2.3
      - widgetsnbextension==3.6.2
      - zipp==3.13.0
